[licenses]
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "MIT",
    "Unicode-3.0",
]

[licenses.private]
ignore = true

[bans]
skip = []
skip-tree = [
    { crate = "windows-sys@0.59", depth = 3 },
    { crate = "windows-sys@0.60", depth = 3 },
]
