.ie /n(.g .ds Aq /(aq
.el .ds Aq '
.TH protomd-schema 1  "schema " 
.SH NAME
protomd/-schema /- Print the schema of the template context on STDOUT
.SH SYNOPSIS
/fBprotomd schema/fR [/fB/-h/fR|/fB/-/-help/fR] 
.SH DESCRIPTION
Print the schema of the template context on STDOUT.
.PP
This documents the structure of the data that is provided to the Jinja template when it is rendered and can help when building a custom template to be used instead of the default.
.SH OPTIONS
.TP
/fB/-h/fR, /fB/-/-help/fR
Print help (see a summary with /*(Aq/-h/*(Aq)
