## Configuration for the protomd Protobuf Markdown generator.

## Optional frontmatter to place at the beginning of each generated file.
##
## For example, in Vitepress you can configure the outline level for the navigation sidebar by
## adding the following configuration as frontmatter:
##
## frontmatter = "outline: [2, 4]"
frontmatter = ""

## Configuration for `markdownlint`.
[markdownlint]
## List of rules to disable.
disable = []

## Symbols used to define the gRPC method type in templates.
##
## Note that these are always encapsulated in backticks to better highlight them in the
## resulting Markdown, therefore HTML.
[request_symbols]
## Single request-response oneshot.
# unary = "unary"
## Client-side streaming.
# client_streaming = "client streaming"
## Server-side streaming.
# server_streaming = "server streaming"
## Bidirectional (both client- and server-side) streaming.
# bidi_streaming = "bidirectional streaming"
